replicaCount: 1
persistence:
  enabled: true
  size: 50Gi
  storageClass: local-path
service:
  type: ClusterIP
ingress:
  enabled: true
  path: /
  hostPath: nexus.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: nexus-tls
      hosts:
        - nexus.example.com
nodeSelector:
  kubernetes.io/hostname: madrid-wk-01
